apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      name: hello-world
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: haziq
        ports:
        - containerPort: 80